# File structure
# Every directive in one line in form 'option=value'
# Lines starting with '#' are comments
# Disk specification can be disk UUID or disk (sub)directory absolute path

# Backup target directory.
b=

# Backup source disk list
# In the form d<idx>=<absolute path or disk UUID> where idx start from 1 to number of disks
# IDX of data disk can't change from run to run!!!
d1=
d2=
# d3=
# d4=
# ...

# Exclude pattern examples
# exclude-dir='/tmp'
# exclude-names='*.log'
# exclude-regex='.*/raid/tmp/.*'
# ...
